### ISSUE TITLE
"Start fresh with no VBL" option prevents new elevation from being created

### ISSUE THREAD

**Issue by alexonyx64** [melek/lib_elevation#19] opened 2021-12-10 20:42 UTC
When selecting the option "start fresh with no vbl," no new elevation is created. There is no error code or other indication that anything has gone wrong. This glitch cannot be reproduced outside of the campaign file in which it was found
[sword coast elevation test copy.cmpgn.zip](https://github.com/melek/lib_elevation/files/7695345/sword.coast.elevation.test.copy.cmpgn.zip)
.

**Comment by melek** [comment] 2023-03-20 15:57
This may be a duplicate of #21, which is resolved in the pending 1.0rc-1. If the issue remains/returns once that is released, let me know!

Closing for now.

**Closed as completed by melek** 2023-03-20 15:57 UTC
Labels: duplicate
