### ISSUE TITLE
Map Options view is hidden so controls cannot be seen or accessed.

### ISSUE THREAD

**Issue by adventuremagic123** [melek/lib_elevation#4] opened 2021-08-21 21:37 UTC
For 1.0a6, "Map Options" view renders so that I can't access its controls.

I have a display on Windows 10 set for Display resolution "3840 x 2160".

![Screenshot 2021-08-21 163523](https://user-images.githubusercontent.com/50708405/130335339-5c8fe86e-7d78-4cd0-8fe3-bdb203edb04f.jpg)

**Comment by adventuremagic123** [comment] 2021-08-21 21:42
I changed the resolution of my display to HD (1280 x 720) and Map Options still appeared the same way.

**Comment by melek** [comment] 2021-08-27 18:41
I don't know why that might be happening! I can't reproduce this so far. 

I will be releasing 1.0b shortly, which overhauls this dialog. Could you please try:

1. Updating to 1.0b as soon as it is available
2. If that doesn't work, if you are on Windows 10 with a High DPI display, even if you lowered the resolution it may still have DPI scaling set for MapTool. Can you try disabling that if it is set in the executable's properties?
3. If that STILL doesn't work, you can use the 'Toggle Fog Hack' and 'Configure faded sight' GM Panel Utilities to change some of the options on the map. You can also edit the `optionsDialog` macro (it is bright aqua colored since I edit it often) to see all the available options you can change manually with `elevation.setMapOption`.

If you can't resolve it by tinkering with `optionsDialog` or the steps above, can you: 

* Provide replicable steps from a blank campaign to get the error
* Provide your hardware specifications in some more detail: Hit Windows+Pause/Break to view your About system dialog, scroll down to the Windows specifications and hit 'Copy', then paste them here, along with any other info you think may help.
* Attach the smallest possible campaign file you can create the exhibits the error.

Thanks!

**Comment by adventuremagic123** [comment] 2021-08-28 15:31
I've already sent Melek more info about this.  For the community, I'll detail things below.  Yes, Melek is completely right -- my 4K display is causing the problem.  When I use a 1600 x 900 display, there's no issue.

I haven't gotten the 4K display to work, yet.  I've tried these settings but they don't seem to have helped -- oh but I didn't follow the instruction for changing the option to "I open this program".  That should do it.  I'll let you know.

https://www.rptools.net/2019/03/windows-10-dpi-scaling-strikes-again/

**Comment by adventuremagic123** [comment] 2021-08-28 15:48
I found the problem.  Here it is ...

![unknown](https://user-images.githubusercontent.com/50708405/131223357-06998dcb-bea9-4167-ae6d-6dc9a0f51a67.png)

Change the above setting to 100% and the text in the Map Options dialog becomes visible.  However, on a 4K display, you can't read text for your apps and Windows because it's now too small.  But at least now we know what's causing it -- so we can now use work-arounds.

**Comment by adventuremagic123** [comment] 2021-08-28 15:50
Potentially, the answer here is to make the dialog resizable as a frame, instead?

**Comment by adventuremagic123** [comment] 2021-08-28 16:03
All of my feedback above was based on 1.0a6.

**Comment by adventuremagic123** [comment] 2021-08-28 16:19
To help out the community, one obvious choice to working around the problem is to decrease the resolution of your 4K display so that you can read text scaled at 100% -- and ask Melek to upgrade his monitor!  :)

**Comment by adventuremagic123** [comment] 2021-08-28 20:43
Somehow, the Map Options dialog is now working at 3840 x 2160 and 150% "Change the size of text, apps, and other items" (I previously had 200% but thought also 150% was not working).

I'm not sure why it is now working.  I am now using 1.0b.  Before, I was reporting on 1.0a6.

**Comment by melek** [comment] 2021-09-04 00:56
Hmm... Sounds like it is somehow fixed in 1.0b, though the issue is weird and obviously hard to reproduce. Maybe there was a tag or other issue that wasn't playing well with Java, since this looks like a Swing/JavaFX error, not anything to do with the library.

Closing for now, but if this happens again I'll re-open or reference a new issue from here.

**Comment by melek** [comment] 2021-10-07 16:31
With help from @adventuremagic123 I've reproduced this issue and tracked down that `<b>` (and other tags and span styles) which bold, underline, or change text color can cause errors on high DPI screens in the Map Dialog.

A fix is being tested for 1.0b6.

**Comment by melek** [comment] 2021-10-30 17:30
This issue has been fixed in 1.0b6. 

This may happen again with future updates; I will try to test dialog changes as we go, but let me know if it comes back!

**Closed as completed by melek** 2021-10-30 17:30 UTC
Labels: bug, limitation
